### ISSUE TITLE
没有看懂试例？

### ISSUE THREAD

**Issue by Zegapaiz** [Molin123/react-molin#10]
看到src文件夹中是一个js文件如app.js对应一个文件夹app对应一个页面吗？可我怎么又在app文件夹中分别看到了index 文件和list文件？list文件不应该是另一个页面吗，我启动服务后看到http://127.0.0.1:1024/home.html#/index 下排版错乱
![image](https://user-images.githubusercontent.com/12904995/28402623-64044990-6d53-11e7-9a7c-fda44f6a5347.png)

# 且点击list后是个空白页。

##  运行npm run start正常 运行npm run start-win报错

**Comment by Molin123** [comment]
app.js对应的是一个spa的入口，app目录下的文件则是spa对应的不同页面。

**Comment by Zegapaiz** [comment]
thanks!再问下config.page.js中配置的页面是只能配置spa的入口文件是吧？还是也能配置spa中的不同页面，不同spa间可以互相跳转吗？

因为看到模板文件中的title是按照 config.page.js 中的配置渲染的，如果不能配置spa中的页面的话怎样实现动态渲染这个title？

**Comment by Molin123** [comment]
@Zegapaiz `config.page.js`配置的是我们最终生成的`.html`文件。如果想在spa不同页面设置title的话可以使用`document.title = 'title';`。不同的spa之间跳转使用`window.location.href`即可。

**Comment by Zegapaiz** [comment]
该框架非常适合我的需求！同时问下是否还有数据层操作呢？
