### ISSUE TITLE
引入antd-mobile 中的Popup组件报错

### ISSUE THREAD

**Issue by Zegapaiz** [Molin123/react-molin#11]
![image](https://user-images.githubusercontent.com/12904995/28573870-b3922ab6-717e-11e7-98f7-2cb39d9e85c3.png)
当我触发事件后执行Popup.show()方法后报如上错误（web环境）
为此我做了如下操作：
更新antd-mobile版本到1.5.0 无效

**Comment by Zegapaiz** [comment]
发现是button组件的问题，当我打开devtool后报这个错
![image](https://user-images.githubusercontent.com/12904995/28601995-1ba74eb4-71ee-11e7-9894-3491299454d8.png)
项目重新npm run start后一切正常，但是每当修改代码保存后自动刷新时就会报错
react-molin是和antd-mobile有兼容问题吗？还是自动刷新的问题？

**Comment by Molin123** [comment]
@Zegapaiz 你可以把代码贴出来，我看一下。

**Comment by Zegapaiz** [comment]
@Molin123 
![image](https://user-images.githubusercontent.com/12904995/28603843-45d3a722-71f9-11e7-99db-99014f23c71f.png)

**Comment by Molin123** [comment]
@Zegapaiz 
```
onClick = () => {
	Popup.show(<div>666</div>)
}
render(){
        return(
            <div>
                     <Button onClick={this.onClick}>显示</Button>
            </div>
        )
    }
```
我试了一下，没发现你说的问题。

**Comment by Zegapaiz** [comment]
@Molin123 
复现步骤
1. npm run start   
2. 使用 chrome浏览器 或者 微信web开发者工具 打开http://127.0.0.1:1024/app.html#/list  并打开控制台console面板
3. 在src/app/list.js中第44行插入``` <Button onClick={onClick}>显示</Button>```
4. 在第37行插入``` const onClick = () => { Popup.show(<div>666</div>)  }```
5. 在第8行引入Popup和Button组件
6. command + s  保存  观察控制台console面板中的信息

**Comment by Molin123** [comment]
@Zegapaiz 按照你的步骤试了一下，也是没有问题的

**Comment by Zegapaiz** [comment]
@Molin123 没有报错吗？是新git下来的代码吗？你本地的和线上仓库中的代码是否有区别？我在另外一个位置新拉下来代码新建一个工程，按照上述过程同样报错

**Comment by Molin123** [comment]
@Zegapaiz 是和master分支一样的

**Comment by Zegapaiz** [comment]
@Molin123 我这边还是报错= =晚上我换台电脑试试

**Comment by Zegapaiz** [comment]
@Molin123 我换了台电脑仍然出现问题,方便留下邮箱吗？我将发送一个录屏说明我的问题

**Comment by Molin123** [comment]
@Zegapaiz 810975746@qq.com
