### ISSUE TITLE
设置host，提个小建议

### ISSUE THREAD

**Issue by hifizz** [Molin123/react-molin#2]
npm start 就不用设置127.0.0.1了，直接在package.json里面指定好吧~

**Comment by Molin123** [comment]
这样写是为了可以指定ip启动，比如使用局域网ip，方便在手机上预览。

**Comment by hifizz** [comment]
嗯，我倒是没有遇到这种需求，一般调试都是在我本机调试，手机预览（或者给别人看）也是查看一下本机ip。

可以做成不给参数则设置为默认的ip和端口。

**Comment by Molin123** [comment]
对的，可以给个默认的，我优化一下。

**Comment by Molin123** [comment]
已经把DevServer的配置单独出来了一个配置文件，默认是127.0.0.1，可以更改。
